{% set name = "MonkeyType" %}
{% set version = "19.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: ecee4162a153c8a0d2151dfc66f06ebb82e4582b0d46281798d908888bb0c9b9
  - folder: src
    url: https://github.com/Instagram/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 497379907318f98def803bba3bd228a3261aabce43f00f460ff76f495016a464

build:
  number: 0
  noarch: python
  entry_points:
    - monkeytype=monkeytype.cli:entry_point_main
  script: cd dist && python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - retype

test:
  source_files:
    - src/tests
  requires:
    - cython
    - django
    - pytest
    - {{ compiler('c') }}
  imports:
    - monkeytype
  commands:
    - monkeytype --help
    - cd src && cd tests
    - python -m pytest -k "not test_includes_otherwise"


about:
  home: https://github.com/Instagram/MonkeyType
  license: BSD-3-Clause
  license_family: BSD
  license_file: src/LICENSE
  summary: Generating type annotations from sampled production types

  description: |
    MonkeyType collects runtime types of function arguments and return values,
    and can automatically generate stub files or even add draft type
    annotations directly to your Python code based on the types collected at
    runtime.

extra:
  recipe-maintainers:
    - bollwyvl
    - nehaljwani
