{% set name = "MonkeyType" %}
{% set version = "19.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 97ee789c37f5ad584bdc7fb949fc6b6254f38acde0f82ec11f8ddcfbe8f534fa
  - folder: src
    url: https://github.com/Instagram/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: f399158fb86cadb043d53f0e202f03efbfa3a1e3cf63f9ba265d8cdb2c650450

build:
  number: 0
  noarch: python
  entry_points:
    - monkeytype=monkeytype.cli:entry_point_main
  script: cd dist && python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - retype

test:
  source_files:
    - src/tests
  requires:
    - cython
    - django
    - pytest
    - gcc
  imports:
    - monkeytype
  commands:
    - monkeytype --help
    - cd src && cd tests
    - python -m pytest -k "not test_includes_otherwise"


about:
  home: https://github.com/Instagram/MonkeyType
  license: BSD-3-Clause
  license_family: BSD
  license_file: src/LICENSE
  summary: Generating type annotations from sampled production types

  description: |
    MonkeyType collects runtime types of function arguments and return values,
    and can automatically generate stub files or even add draft type
    annotations directly to your Python code based on the types collected at
    runtime.

extra:
  recipe-maintainers:
    - bollwyvl
    - nehaljwani
