{% set name = "MonkeyType" %}
{% set version = "20.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 429228b3a731f9082e4ead00b871e7b75aeee86b65b5ac05fc35dc9254730a7c
  - folder: src
    url: https://github.com/Instagram/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 714db9f91771ef10c6056a82d9702c2f53dcb991328dbe4c9f7ef637fae7fd28

build:
  number: 0
  noarch: python
  entry_points:
    - monkeytype=monkeytype.cli:entry_point_main
  script: cd dist && python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - pip
    - python >=3.6
    - setuptools
  run:
    - mypy_extensions
    - python >=3.6
    - libcst

test:
  source_files:
    - src/tests
  requires:
    - cython
    - django
    - pytest
    - {{ compiler('c') }}
  imports:
    - monkeytype
  commands:
    - monkeytype --help
    - cd src && cd tests
    - python -m pytest -k "not test_includes_otherwise"


about:
  home: https://github.com/Instagram/MonkeyType
  license: BSD-3-Clause
  license_family: BSD
  license_file: src/LICENSE
  summary: Generating type annotations from sampled production types

  description: |
    MonkeyType collects runtime types of function arguments and return values,
    and can automatically generate stub files or even add draft type
    annotations directly to your Python code based on the types collected at
    runtime.

extra:
  recipe-maintainers:
    - bollwyvl
    - nehaljwani
