travis:
  secure:
    BINSTAR_TOKEN: XA5LHkx2LlgQX7s3sh47BMgzneCSpA8CbM22Wkj/X32Jv6lfZBFQWlp7S2C9tLSvzsyzMvuuIMEo6PpOO0P54i4Ug5zwWdjALDTAu0myCmZuc69Lzvys0Z3MFETH0W5VxamFf/1AASp2UddPNy38v3ZLkgFCFZ0v9Ec/ceulM0tlhrXSeUg1YQymkSvxmDZXPoCB3ML3WBqGBfRViEYzW+kyunr9f0xMZ+Oe7I88cmVEtvcgG57UQfzI1nNKbV/2IFC+kxL2lB2bLdmzdHT1dWZrLCuMfB1JeorOp9to1HCcI4q6spHE6dpM4MzUZEunsqhFSAMff+uirlH7xt3J6oqZq5n+W3PFzsdmidQI4gtLgowithxQug662X+l02Ou3QdejBS0dtCywyWHuDLh7st3vqDSrAwjz/88cE8vndrt7RYFhpYzJmQJdiBfOswYUIlQkh5ukKSM30+Asj36z2DyLqzAO5+wQjaeNQdt/DU11v1z/6mMKtkmMoWeh/MP0zko1tV5HJHESGOZCSm7EipRxU3qb7RBRzGFlqlukX9nqOOCjs9KxPIShYTzpDaQ1RFBOUgaV5YvP0rTUCNPBu1lMnmfs3ylkkO1WXnwaGG+5izG2bXLS1e+Rm0dUaAG93xTrAguZLXL3x2NU3kZNFwoS9tNKID6jiKLNIW5dak=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
