travis:
  secure:
    BINSTAR_TOKEN: bA5AOyzY7I5jAkBnt6aE+oPLeBABSrWGH/7n0dGdTyCwMOLtajG2tsvI41vEdcBvGEbhOtR+QmWD6G6s9yNBgzX50Mbk4xSymElIfhV3lOoal+3UZwpFLlKXafSx/qDhlO8bZ2wfO+wy8lLR/so8os+cY0cOo0t/rXwbH3itpuMxDay3Pzqd5LV3+c5inXualpP9LADsL4wHDs/E35wet96Ip1zzFLDwOmGeoGvYKGybh8zEgVABKc3DBoCfPRlQq1eMEekO2AhSG5tlzNmfPFOk2PpY4xBYI3Pb3eR6dSne42sKeHBRGpEUsJAQ1mKm5GI7CbkOAk0eqMjcUiCjB2oqW1PepseFUFfrGsVLjlL2z0ypDsH0yvWC/vJ+OnBr+hj3pLIv6ZlWfBvwhgSni7e258W5jOtAC95ZjIfLMe6o7sWarpaJPLfVABhALoH+i6X53srkOTnloKYCwOU0I1ekQS5N8sFFm3PwioUgGbbNjZfdpAJzh8xSvUjyXG17Z3XRYoBYqZq+GCZ9gJVKrfSaYCjiGQ9gjzwFMhkTSpBHuHDSoCCxuta0YA2TJAgUJP+hgkBX+NQ8YvSlZqDJHqcwGyc2ap20qj4F9RXQx9L6kyBisS7MMY80l+VRQIop8OKk4bvbtJmKNDitChdDdOQGqwHc5+MShowCt8S54dw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
